# Generated by Django 5.1.1 on 2024-09-05 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='universityclasses',
            old_name='Course_number',
            new_name='course_number',
        ),
        migrations.RenameField(
            model_name='universityclasses',
            old_name='Instructor_name',
            new_name='instructor_name',
        ),
    ]
